/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.server;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class ServerModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public ServerModElements() {
		sounds.put(new ResourceLocation("server", "policia_en_accion"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("server", "policia_en_accion")));
		sounds.put(new ResourceLocation("server", "yummy"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "yummy")));
		sounds.put(new ResourceLocation("server", "asco_puaj"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "asco_puaj")));
		sounds.put(new ResourceLocation("server", "saciado"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "saciado")));
		sounds.put(new ResourceLocation("server", "alone"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "alone")));
		sounds.put(new ResourceLocation("server", "de_sastre"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "de_sastre")));
		sounds.put(new ResourceLocation("server", "quizas"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "quizas")));
		sounds.put(new ResourceLocation("server", "sufremamon_disk"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("server", "sufremamon_disk")));
		sounds.put(new ResourceLocation("server", "resistiresound"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("server", "resistiresound")));
		sounds.put(new ResourceLocation("server", "popola"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "popola")));
		sounds.put(new ResourceLocation("server", "blursound"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "blursound")));
		sounds.put(new ResourceLocation("server", "rammstein"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "rammstein")));
		sounds.put(new ResourceLocation("server", "greenday"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "greenday")));
		sounds.put(new ResourceLocation("server", "the_nights"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "the_nights")));
		sounds.put(new ResourceLocation("server", "mood"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "mood")));
		sounds.put(new ResourceLocation("server", "watermelon_sugar"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("server", "watermelon_sugar")));
		sounds.put(new ResourceLocation("server", "montero"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "montero")));
		sounds.put(new ResourceLocation("server", "ibaisong"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "ibaisong")));
		sounds.put(new ResourceLocation("server", "cakebytheocean"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("server", "cakebytheocean")));
		sounds.put(new ResourceLocation("server", "delgadito"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "delgadito")));
		sounds.put(new ResourceLocation("server", "the_animals"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "the_animals")));
		sounds.put(new ResourceLocation("server", "phineasdisk"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "phineasdisk")));
		sounds.put(new ResourceLocation("server", "el_anillo"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "el_anillo")));
		sounds.put(new ResourceLocation("server", "gemido"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "gemido")));
		sounds.put(new ResourceLocation("server", "alto_policia"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "alto_policia")));
		sounds.put(new ResourceLocation("server", "orden_en_la_sala"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("server", "orden_en_la_sala")));
		sounds.put(new ResourceLocation("server", "shower"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "shower")));
		sounds.put(new ResourceLocation("server", "pilots21"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "pilots21")));
		sounds.put(new ResourceLocation("server", "musicatristenaruto"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("server", "musicatristenaruto")));
		sounds.put(new ResourceLocation("server", "memyselfandi"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "memyselfandi")));
		sounds.put(new ResourceLocation("server", "esgratis"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "esgratis")));
		sounds.put(new ResourceLocation("server", "princesas"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "princesas")));
		sounds.put(new ResourceLocation("server", "sound123"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "sound123")));
		sounds.put(new ResourceLocation("server", "quemaspues"), new net.minecraft.util.SoundEvent(new ResourceLocation("server", "quemaspues")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("server").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == ServerModElements.ModElement.class)
						elements.add((ServerModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(ServerModElements.ModElement::initElements);
		MinecraftForge.EVENT_BUS.register(new ServerModVariables(this));
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}
	private int messageID = 0;
	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		ServerMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final ServerModElements elements;
		protected final int sortid;
		public ModElement(ServerModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
